[project]
name = "aic4970"
version = "0.1.0"
description = "Code for aic4970"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
